[tool.poetry]
name = "lager"
version = "0.6.0"
description = "ez lager"
authors = ["jesse rubin <jessekrubin@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.5"
python-json-logger = "^0.1.11"
structlog = "^19.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
